repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v22.1.4"
    hooks:
      - id: clang-format
  - repo: https://github.com/f-koehler/qml-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: qmlformat
      # - id: qmllint
  - repo: https://github.com/neocmakelsp/neocmakelsp
    rev: v0.10.2
    hooks:
      - id: neocmakelsp-format
