classDiagram
    Account <|-- NetbirdAccount
    Account <|-- TailscaleAccount
    AccountModel~Account~ <|-- NetbirdAccountModel
    AccountModel~Account~ <|-- TailscaleAccountModel
    NetbirdAccount "1" o--o "0..1" NetbirdNetwork
    NetbirdAccountModel o-- NetbirdAccount
    NetbirdNetwork *-- NetbirdNetworkNode
    NetbirdNetworkNode *-- NetbirdNodeProperties
    NetbirdNodeModel o-- NetbirdNetwork
    NetworkNode~Properties~ <|-- NetbirdNetworkNode
    NetworkNode~Properties~ <|-- TailscaleNetworkNode
    NodeProperties <|-- NetbirdNodeProperties
    NodeProperties <|-- TailscaleNodeProperties
    QAbstractListModel <|-- AccountModel~Account~
    QAbstractListModel <|-- NodeModel~Node~
    QAbstractListModel <|-- TailscaleMullvadCountryModel
    QObject <|-- Account
    QObject <|-- MeshState
    QObject <|-- NetworkNode~Properties~
    QObject <|-- Network~Node~
    QObject <|-- NodeProperties
    QObject <|-- QAbstractListModel
    QObject <|-- QSortFilterProxyModel
    QObject <|-- TailscaleAccountsClient
    QObject <|-- TailscaleClient
    QObject <|-- TailscaleNetworkClient
    QObject <|-- TailscaleSettingsClient
    QSortFilterProxyModel <|-- TailscaleExitNodeModel
    QSortFilterProxyModel <|-- TailscaleMullvadExitNodeModel
    TailscaleAccount o--o TailscaleNetwork
    TailscaleAccountModel o-- TailscaleAccount
    TailscaleClient *-- TailscaleAccountsClient
    TailscaleClient *-- TailscaleNetworkClient
    TailscaleClient *-- TailscaleSettingsClient
    TailscaleExitNodeModel o-- TailscaleNodeModel
    TailscaleMullvadExitNodeModel o-- TailscaleExitNodeModel
    TailscaleNetwork *-- TailscaleNetworkNode
    TailscaleNetworkNode *-- TailscaleNodeProperties
    TailscaleNodeModel o-- TailscaleNetwork
    

    namespace Qt {
        class QObject {
        }
        class QAbstractListModel {
            <<abstract>>
        }
        class QSortFilterProxyModel {
        }
    }
    
    MeshState *-- "0..*" NetbirdAccount
    MeshState *-- "0..*" NetbirdNetwork
    MeshState *-- "0..*" TailscaleAccount
    MeshState *-- "0..1" TailscaleNetwork
    MeshState *-- "0..1" TailscaleUpdater
    class MeshState {
        -QVector~QPointer TailscaleAccount~ tailscaleAccounts
        -QPointer~TailscaleNetwork~ tailscaleNetwork
        -QPointer~TailscaleUpdater~
        -QVector~QPointer NetbirdAccount~ netbirdAccounts
        -QVector~QPointer NetbirdNetwork~ netbirdNetworks
        +getTailscaleAccounts() QVector~QPointer TailscaleAccount~
        +getNetbirdAccounts() QVector~QPointer NetbirdAccount~
        +getTailscaleNetwork() TailscaleNetwork&ast;
        +getNetbirdNetworks() QVector~QPointer NetbirdNetwork~
    }
    
    QObject <|-- TailscaleUpdater
    TailscaleUpdater -- TailscaleNetwork
    TailscaleUpdater -- TailscaleNodeProperties
    TailscaleUpdater -- Location
    TailscaleUpdater -- PBTailscaleStatus
    TailscaleUpdater -- PBTailscalePeer
    TailscaleUpdater -- PBTailscaleLocation
    class TailscaleUpdater {
        <<interface>>
        -QPointer~QTimer~ updateTimer
        +update(PBTailscaleStatus status, TailscaleNetwork network)
        +update(PBTailscalePeer peer, TailscaleNodeProperties properties)
        +update(PBTailscaleLocation location, Location loc)
    }
    
    QObject <|-- Location
    TailscaleNodeProperties "1" *-- "1" Location
    namespace Nodes {
        class Location {
            -QString countryCode
            -QString countryName
            -QString cityCode
            -QString cityName
            -double longitude
            -double latitude
            +getCountryCode() const QString&
            +getCountryName() const QString&
            +getCityCode() const QString&
            +getLongitude() double
            +getLatitutde() double
        }
        class NodeProperties {
           <<abstract>>
          -QString id
          -QString name
          -QString publicKey
          -QVector~QString~ ipAddresses
          +getId() const QString&
          +getName() const QString&
          +getPublicKey() const QString&
          +getIpAddresses() const QVector~QString~
        }
        class TailscaleNodeProperties {
          -QVector~QString~ tags
          -bool exitNode
          -QString dnsName
          -QString operatingSystem
          -QDateTime lastSeenTime
          -QDateTime creationTime
          -QPointer~Location~ location
          +getTags() QVector~QString~
          +isExitNode() bool
          +getDnsName() const QString&
          +getOperatingSystem() const QString&
          +getLastSeenTime() const QDateTime&
          +getCreationTime() const QDateTime&
          +getLocation() const Location&
        }
        class NetbirdNodeProperties~Properties~ {
        }
        class NetworkNode {
            <<abstract>>
            +getProperties() Properties&ast;
        }
        class TailscaleNetworkNode {
            -QPointer~TailscaleNodeProperties~ properties
        }
        class NetbirdNetworkNode {
            -QPointer~NetbirdNodeProperties~ properties
        }
    }

    Network~Node~ <|-- NetbirdNetwork
    Network~Node~ <|-- TailscaleNetwork
    namespace Networks {
        class Network~Node~  {
            <<abstract>>
            +getNodes() QHash~QString,QPointer Node~&
        }
        class TailscaleNetwork {
            -nodes: QHash~QString,QPointer TailscaleNetworkNode~
        }
        class NetbirdNetwork {
            -nodes: QHash~QString,QPointer NetbirdNetworkNode~
        }
    }

    namespace Accounts {
        class Account {
            <<abstract>>
            -name: QString
            +getName() const QString&
        }
        class TailscaleAccount {
        }
        class NetbirdAccount {
        }
    }
        
    namespace LocalClients {
        class TailscaleClient {
            -QPointer<TailscaleNetworkClient> networkClient
            -QPointer<TailscaleAccountsClient> accountsClient
            -QPointer<TailscaleSettingsClient> settingsClient
            +getNetworkClient() TailscaleNetworkClient&ast;
            +getAccountsClient() TailscaleAccountsClient&ast;
            +getSettingsClient() TailscaleSettingsClient&ast;
        }
        class TailscaleNetworkClient {
            +up()
            +down()
        }
        class TailscaleAccountsClient {
            +list()
            +switch()
        }
        class TailscaleSettingsClient {
            +isAcceptingRoutes() bool
            +setAcceptingRoutes(bool value) bool
            +isAcceptingExitNode() bool
            +setAdvertisingExitNode(bool value) bool
            +getHostname() QString
            +setHostname(name)
        }
    }

    NodeModel~Node~ <|-- NetbirdNodeModel
    NodeModel~Node~ <|-- TailscaleNodeModel
    namespace Models {
        class NodeModel~Node~ {
            <<abstract>>
        }
        class TailscaleNodeModel {
        }
        class NetbirdNodeModel {
        }
        class TailscaleExitNodeModel {
        }
        class TailscaleMullvadExitNodeModel {
        }
        class AccountModel~Account~ {
            <<abstract>>
        }
        class TailscaleAccountModel {
        }
        class NetbirdAccountModel {
        }
        class TailscaleMullvadCountryModel {
        }
    }
    
    PBTailscaleStatus "1" *-- "1" PBTailscalePeer
    PBTailscaleStatus "1" *-- "0..*" PBTailscalePeer
    PBTailscaleStatus "1" *-- "1" PBTailscaleState
    PBTailscalePeer "1" *-- "0..1" PBTailscaleLocation
    namespace Protobuf {
        class PBTailscaleStatus {
            PBTailscaleState state
            PBTailscalePeer self
            repeated PBTailscalePeer peers
            repeated string health
        }
        class PBTailscalePeer {
            +string id
            +string publicKey
            +string hostName
            +string dnsName
            +string operatingSystem
            +repeated string ipAddresses
            +repeated string tags
            +Timestamp lastSeenTime
            +Timestamp createdTime
            +bool exitNode
            +optional PBTailscaleLocation location
        }
        class PBTailscaleLocation {
            +string country
            +string countryCode
            +string city
            +string cityCode
            +double longitude
            +double latitude
        }
        class PBTailscaleState {
            +string version
            +string backendState
            +bool tun
        }
    }