name: CI
on:
  push:
    branches:
      - fk/kf6-experiment
  pull_request:
    branches:
      - fk/kf6-experiment
jobs:
  flatpak_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4
      - name: Update apt cache.
        run: sudo apt-get update -yq
      - name: Install flatpak-builder.
        run: sudo apt-get install -yq flatpak-builder flatpak
      - name: Add flathub remote.
        run: flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Install Builder.
        run: flatpak install --user -y flathub org.flatpak.Builder
      - name: Validate manifest.
        run: flatpak run --command=flatpak-builder-lint org.flatpak.Builder manifest org.fkoehler.KTailctl.yml
      - name: Install external data checker.
        run: flatpak install --user -y flathub org.flathub.flatpak-external-data-checker
      - name: Check external data.
        run: flatpak run org.flathub.flatpak-external-data-checker --check-outdated org.fkoehler.KTailctl.yml
      - name: Install KDE SDK.
        run: flatpak install --user -y flathub org.kde.Sdk//6.5 org.kde.Platform/x86_64/6.5
      - name: Install Go SDK.
        run: flatpak install --user -y flathub org.freedesktop.Sdk.Extension.golang/x86_64/22.08
      - name: Install LLVM SDK.
        run: flatpak install --user -y flathub runtime/org.freedesktop.Sdk.Extension.llvm16/x86_64/22.08
      - name: Build.
        run: flatpak-builder --user --install --force-clean build-dir org.fkoehler.KTailctl.yml
